####################################################
# Application
####################################################

spring.application.name=gateway-service

server.port=8080

####################################################
# Eureka
####################################################

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

####################################################
# Gateway Discovery
####################################################

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

####################################################
# Global CORS
####################################################
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:5173

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true

####################################################
# Gateway Routes
####################################################

# ============================
# AUTH SERVICE
# ============================

spring.cloud.gateway.server.webflux.routes[0].id=auth-service

spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE

spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# ============================
# USER APIs (Inside Auth Service)
# ============================

spring.cloud.gateway.server.webflux.routes[1].id=user-service

spring.cloud.gateway.server.webflux.routes[1].uri=lb://AUTH-SERVICE

spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/user/**

# ============================
# PRODUCT APIs (Inside Auth Service)
# ============================

spring.cloud.gateway.server.webflux.routes[2].id=product-service

spring.cloud.gateway.server.webflux.routes[2].uri=lb://AUTH-SERVICE

spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/products/**

# ============================
# ORDER SERVICE
# ============================

spring.cloud.gateway.server.webflux.routes[3].id=order-service

spring.cloud.gateway.server.webflux.routes[3].uri=lb://ORDER-SERVICE

spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/orders/**

# ============================
# PAYMENT SERVICE
# ============================

spring.cloud.gateway.server.webflux.routes[4].id=payment-service

spring.cloud.gateway.server.webflux.routes[4].uri=lb://PAYMENT-SERVICE

spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/payments/**

# ============================
# INVENTORY SERVICE
# ============================

spring.cloud.gateway.server.webflux.routes[5].id=inventory-service

spring.cloud.gateway.server.webflux.routes[5].uri=lb://INVENTORY-SERVICE

spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/inventory/**

# ============================
# DELIVERY SERVICE
# ============================

spring.cloud.gateway.server.webflux.routes[6].id=delivery-service

spring.cloud.gateway.server.webflux.routes[6].uri=lb://DELIVERY-SERVICE

spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/delivery/**

####################################################
# CUSTOMER PROFILE
####################################################

spring.cloud.gateway.server.webflux.routes[7].id=customer-profile

spring.cloud.gateway.server.webflux.routes[7].uri=lb://AUTH-SERVICE

spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/customer/**

####################################################
# CART SERVICE
####################################################

spring.cloud.gateway.server.webflux.routes[8].id=cart-service

spring.cloud.gateway.server.webflux.routes[8].uri=lb://CART-SERVICE

spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/cart/**

####################################################
# Actuator
####################################################
####################################################
# GOOGLE OAUTH2
####################################################

# Google OAuth2 Authorization
spring.cloud.gateway.server.webflux.routes[9].id=auth-oauth2-authorization
spring.cloud.gateway.server.webflux.routes[9].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/oauth2/authorization/**

# Google OAuth2 Callback
spring.cloud.gateway.server.webflux.routes[10].id=auth-oauth2-callback
spring.cloud.gateway.server.webflux.routes[10].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/login/oauth2/**

management.endpoints.web.exposure.include=*

management.tracing.enabled=true
management.tracing.sampling.probability=1.0

logging.pattern.correlation=[${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]

####################################################
# Gateway Debug Logging
####################################################

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.reactor.netty.http.client=DEBUG

####################################################
# Reactor Context Propagation
####################################################

spring.reactor.context-propagation=auto