spring.application.name=ORDER-SERVICE

server.port=8083

# =================================================
# Database
# =================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# =================================================
# JPA
# =================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =================================================
# Eureka
# =================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# =================================================
# Distributed Tracing
# =================================================

management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# =================================================
# Log Trace ID + Span ID
# =================================================

logging.pattern.correlation=[${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]