spring.application.name=eureka-server

server.port=8761

# This application itself should not register with Eureka
eureka.client.register-with-eureka=false

# It should not try to fetch the registry
eureka.client.fetch-registry=false

# Development settings
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000