#spring.application.name=config-server

#server.port=8888

# Git configuration repository
#spring.cloud.config.server.git.uri=file:///E:/MICROSERVICES/ECOMMERCE-MICROSERVICES/ecommerce-config

#spring.cloud.config.server.git.default-label=main


spring.application.name=config-server

server.port=8888

# GitHub Config Repository
spring.cloud.config.server.git.uri=https://github.com/nanajiitdev/nanokart-config.git
spring.cloud.config.server.git.default-label=main