####################################################
# Application
####################################################

spring.application.name=email-service

server.port=8095

####################################################
# RabbitMQ
####################################################

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

####################################################
# Gmail SMTP
####################################################

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


spring.mail.username=nanaji.itdev@gmail.com

#spring.mail.password=jkyg iuzz yeuj scwo
spring.mail.password=jkygiuzzyeujscwo

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

####################################################
# Eureka
####################################################

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true

####################################################
# Actuator
####################################################

management.endpoints.web.exposure.include=*

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
logging.pattern.correlation=[${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]
spring.rabbitmq.listener.simple.observation-enabled=true

spring.reactor.context-propagation=auto
